version: 0.2

phases:
  build:
    commands:

     - echo Entered the build phase...
     - mvn clean package
  post_build:
    commands:
     - echo Build completed successfully
artifacts:
  files:
      - target/cde-027-pipeline-gupta-shubh.jar
  discard-paths: yes